# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.runs/my_rm_synth_1/pfm_dynamic.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "my_rm_synth_1" START { ROLLUP_AUTO }
set_param project.enablePRFlowIPI 1
set_param bd.enable_dpa 1
set_param bd.debug_profile.script /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/.local/debug_profile_automation.tcl
set_param bd.resize_sdx_addr_width 1
set_param bd.ForceAppCoreUpgrade 1
set_param bd.skipSupportedIPCheck 1
set_param hd.Visual 0
set_param project.loadTopLevelOOCConstrs 1
set_param ips.enableSLRParameter 2
set_param compiler.enablePerformanceTrace 1
set_param general.maxThreads 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu250-figd2104-2L-e
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/.local/hw_platform/board} [current_project]
set_property board_part xilinx.com:au250:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/int/xo/ip_repo/xilinx_com_hls_hyst_1_0
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/int/xo/ip_repo/xilinx_com_hls_nms_1_0
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/int/xo/ip_repo/xilinx_com_hls_gau_1_0
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/int/xo/ip_repo/xilinx_com_hls_sobel_1_0
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/.local/hw_platform/iprepo
  /opt/xilinx/Vitis/2020.1/data/cache/xilinx
  /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/.local/hw_platform/ipcache
  /opt/xilinx/Vitis/2020.1/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/luoyanl2/ece527_taskpar/fpga_kernels/.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic.bd
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/ip/ip_0/bd_ebbe_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/bd_0/bd_ebbe_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_debug_bridge_xsdbm_0/pfm_dynamic_debug_bridge_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_periph_null_0/pfm_dynamic_regslice_periph_null_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_periph_null_0/pfm_dynamic_regslice_periph_null_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_1/bd_27a1_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_1/bd_27a1_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_2/bd_27a1_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_2/bd_27a1_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_3/bd_27a1_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_3/bd_27a1_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_4/bd_27a1_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_5/bd_27a1_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_6/bd_27a1_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_7/bd_27a1_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_8/bd_27a1_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_12/bd_27a1_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_13/bd_27a1_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_14/bd_27a1_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_15/bd_27a1_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_16/bd_27a1_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_17/bd_27a1_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_21/bd_27a1_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_22/bd_27a1_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_23/bd_27a1_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_27/bd_27a1_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_28/bd_27a1_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_29/bd_27a1_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_30/bd_27a1_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_34/bd_27a1_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_35/bd_27a1_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_36/bd_27a1_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_40/bd_27a1_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_41/bd_27a1_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_42/bd_27a1_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_43/bd_27a1_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_47/bd_27a1_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_48/bd_27a1_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_49/bd_27a1_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_53/bd_27a1_s06a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_54/bd_27a1_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_55/bd_27a1_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_56/bd_27a1_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_60/bd_27a1_s07a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_61/bd_27a1_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_62/bd_27a1_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_66/bd_27a1_s08a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_67/bd_27a1_sawn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_68/bd_27a1_swn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_69/bd_27a1_sbn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_70/bd_27a1_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_71/bd_27a1_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_72/bd_27a1_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_73/bd_27a1_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_74/bd_27a1_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_1/ip/ip_75/bd_27a1_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_9/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_17/bd_d216_vip_S00_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_18/bd_d216_vip_S04_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_19/bd_d216_vip_S05_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_20/bd_d216_vip_S06_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_21/bd_d216_vip_S07_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_22/bd_d216_vip_S08_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_23/bd_d216_vip_S09_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_24/bd_d216_vip_S10_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_25/bd_d216_vip_S11_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_0/bd_065e_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_0/bd_065e_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_1/bd_065e_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_1/bd_065e_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_2/bd_065e_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_3/bd_065e_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_6/bd_065e_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_9/bd_065e_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/ip/ip_10/bd_065e_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_2/bd_065e_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/ip_0/bd_d216_ddr4_mem00_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/ip_0/bd_d216_ddr4_mem00_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/ip_1/par/bd_d216_ddr4_mem00_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/bd_d216_ddr4_mem00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/par/bd_d216_ddr4_mem00_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_11/bd_d216_psr_ddr4_mem00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_11/bd_d216_psr_ddr4_mem00_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_11/bd_d216_psr_ddr4_mem00_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_12/bd_d216_ddr4_mem00_ctrl_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_12/bd_d216_ddr4_mem00_ctrl_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_12/bd_d216_ddr4_mem00_ctrl_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_8/bd_d216_psr_ctrl_interconnect_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_8/bd_d216_psr_ctrl_interconnect_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_8/bd_d216_psr_ctrl_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_16/bd_d216_interconnect_ddrmem_ctrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_26/bd_d216_vip_DDR4_MEM00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_vip_ui_clk_DDR4_MEM00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_28/bd_d216_vip_ui_rst_DDR4_MEM00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_29/bd_d216_vip_ctrl_DDR4_MEM00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/bd_d216_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_0/pfm_dynamic_axi_cdc_data_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_0/pfm_dynamic_axi_cdc_data_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_0/pfm_dynamic_axi_cdc_data_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_0/pfm_dynamic_axi_cdc_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_0/pfm_dynamic_axi_cdc_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_0/pfm_dynamic_axi_gpio_null_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_0/pfm_dynamic_axi_user_slrcrossing_mi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_0/pfm_dynamic_axi_user_slrcrossing_mi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_control_mgntpf_0/pfm_dynamic_axi_vip_control_mgntpf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_ctrl_userpf_0/pfm_dynamic_axi_vip_ctrl_userpf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_data_0/pfm_dynamic_axi_vip_data_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_mgntpf_0/pfm_dynamic_regslice_control_mgntpf_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_mgntpf_0/pfm_dynamic_regslice_control_mgntpf_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_mgntpf_0/pfm_dynamic_regslice_control_mgntpf_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_mgntpf_0/pfm_dynamic_regslice_control_mgntpf_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_0/pfm_dynamic_regslice_data_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_0/pfm_dynamic_regslice_data_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_0/pfm_dynamic_regslice_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_0/pfm_dynamic_regslice_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_0/pfm_dynamic_psreset_gate_pr_control_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_0/pfm_dynamic_psreset_gate_pr_data_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_0/pfm_dynamic_psreset_gate_pr_data_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_0/pfm_dynamic_psreset_gate_pr_data_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_0/pfm_dynamic_psreset_gate_pr_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_0/pfm_dynamic_psreset_gate_pr_data_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_0/pfm_dynamic_psreset_gate_pr_kernel_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_0/pfm_dynamic_psreset_gate_pr_kernel2_0_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_1/pfm_dynamic_axi_cdc_data_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_1/pfm_dynamic_axi_cdc_data_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_1/pfm_dynamic_axi_cdc_data_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_1/pfm_dynamic_axi_cdc_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_1/pfm_dynamic_axi_cdc_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_1/pfm_dynamic_axi_gpio_null_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_1/pfm_dynamic_axi_gpio_null_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_1/pfm_dynamic_axi_gpio_null_1.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_1/pfm_dynamic_axi_user_slrcrossing_mi_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_1/pfm_dynamic_axi_user_slrcrossing_mi_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_0/pfm_dynamic_axi_user_slrcrossing_si_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_0/pfm_dynamic_axi_user_slrcrossing_si_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_data_1/pfm_dynamic_axi_vip_data_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_1/pfm_dynamic_regslice_data_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_1/pfm_dynamic_regslice_data_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_1/pfm_dynamic_regslice_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_1/pfm_dynamic_regslice_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_1/pfm_dynamic_psreset_gate_pr_control_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_1/pfm_dynamic_psreset_gate_pr_control_1.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_1/pfm_dynamic_psreset_gate_pr_control_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_1/pfm_dynamic_psreset_gate_pr_control_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_1/pfm_dynamic_psreset_gate_pr_control_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_1/pfm_dynamic_psreset_gate_pr_data_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_1/pfm_dynamic_psreset_gate_pr_data_1.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_1/pfm_dynamic_psreset_gate_pr_data_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_1/pfm_dynamic_psreset_gate_pr_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_1/pfm_dynamic_psreset_gate_pr_data_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_1/pfm_dynamic_psreset_gate_pr_kernel_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_1/pfm_dynamic_psreset_gate_pr_kernel_1.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_1/pfm_dynamic_psreset_gate_pr_kernel_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_1/pfm_dynamic_psreset_gate_pr_kernel_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_1/pfm_dynamic_psreset_gate_pr_kernel_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_1/pfm_dynamic_psreset_gate_pr_kernel2_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_1/pfm_dynamic_psreset_gate_pr_kernel2_1.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_1/pfm_dynamic_psreset_gate_pr_kernel2_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_1/pfm_dynamic_psreset_gate_pr_kernel2_1_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_1/pfm_dynamic_psreset_gate_pr_kernel2_1_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_2/pfm_dynamic_axi_cdc_data_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_2/pfm_dynamic_axi_cdc_data_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_2/pfm_dynamic_axi_cdc_data_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_2/pfm_dynamic_axi_cdc_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_2/pfm_dynamic_axi_cdc_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_2/pfm_dynamic_axi_gpio_null_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_2/pfm_dynamic_axi_gpio_null_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_2/pfm_dynamic_axi_gpio_null_2.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_2/pfm_dynamic_axi_user_slrcrossing_mi_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_mi_2/pfm_dynamic_axi_user_slrcrossing_mi_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_1/pfm_dynamic_axi_user_slrcrossing_si_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_1/pfm_dynamic_axi_user_slrcrossing_si_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_data_2/pfm_dynamic_axi_vip_data_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_2/pfm_dynamic_regslice_data_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_2/pfm_dynamic_regslice_data_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_2/pfm_dynamic_regslice_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_2/pfm_dynamic_regslice_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_2/pfm_dynamic_psreset_gate_pr_control_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_2/pfm_dynamic_psreset_gate_pr_control_2.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_2/pfm_dynamic_psreset_gate_pr_control_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_2/pfm_dynamic_psreset_gate_pr_control_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_2/pfm_dynamic_psreset_gate_pr_control_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_2/pfm_dynamic_psreset_gate_pr_data_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_2/pfm_dynamic_psreset_gate_pr_data_2.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_2/pfm_dynamic_psreset_gate_pr_data_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_2/pfm_dynamic_psreset_gate_pr_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_2/pfm_dynamic_psreset_gate_pr_data_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_2/pfm_dynamic_psreset_gate_pr_kernel_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_2/pfm_dynamic_psreset_gate_pr_kernel_2.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_2/pfm_dynamic_psreset_gate_pr_kernel_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_2/pfm_dynamic_psreset_gate_pr_kernel_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_2/pfm_dynamic_psreset_gate_pr_kernel_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_2/pfm_dynamic_psreset_gate_pr_kernel2_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_2/pfm_dynamic_psreset_gate_pr_kernel2_2.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_2/pfm_dynamic_psreset_gate_pr_kernel2_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_2/pfm_dynamic_psreset_gate_pr_kernel2_2_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_2/pfm_dynamic_psreset_gate_pr_kernel2_2_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_3/pfm_dynamic_axi_cdc_data_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_3/pfm_dynamic_axi_cdc_data_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_3/pfm_dynamic_axi_cdc_data_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_3/pfm_dynamic_axi_cdc_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_cdc_data_3/pfm_dynamic_axi_cdc_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_3/pfm_dynamic_axi_gpio_null_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_3/pfm_dynamic_axi_gpio_null_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_gpio_null_3/pfm_dynamic_axi_gpio_null_3.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_2/pfm_dynamic_axi_user_slrcrossing_si_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_user_slrcrossing_si_2/pfm_dynamic_axi_user_slrcrossing_si_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_axi_vip_data_3/pfm_dynamic_axi_vip_data_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_3/pfm_dynamic_regslice_data_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_3/pfm_dynamic_regslice_data_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_3/pfm_dynamic_regslice_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_data_3/pfm_dynamic_regslice_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_3/pfm_dynamic_psreset_gate_pr_control_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_3/pfm_dynamic_psreset_gate_pr_control_3.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_3/pfm_dynamic_psreset_gate_pr_control_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_3/pfm_dynamic_psreset_gate_pr_control_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_control_3/pfm_dynamic_psreset_gate_pr_control_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_3/pfm_dynamic_psreset_gate_pr_data_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_3/pfm_dynamic_psreset_gate_pr_data_3.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_3/pfm_dynamic_psreset_gate_pr_data_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_3/pfm_dynamic_psreset_gate_pr_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_data_3/pfm_dynamic_psreset_gate_pr_data_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_3/pfm_dynamic_psreset_gate_pr_kernel_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_3/pfm_dynamic_psreset_gate_pr_kernel_3.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_3/pfm_dynamic_psreset_gate_pr_kernel_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_3/pfm_dynamic_psreset_gate_pr_kernel_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel_3/pfm_dynamic_psreset_gate_pr_kernel_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_3/pfm_dynamic_psreset_gate_pr_kernel2_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_3/pfm_dynamic_psreset_gate_pr_kernel2_3.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_3/pfm_dynamic_psreset_gate_pr_kernel2_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_3/pfm_dynamic_psreset_gate_pr_kernel2_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_psreset_gate_pr_kernel2_3/pfm_dynamic_psreset_gate_pr_kernel2_3_slr.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_xbar_3/pfm_dynamic_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_xbar_4/pfm_dynamic_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_xbar_5/pfm_dynamic_xbar_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_xbar_6/pfm_dynamic_xbar_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_gau_1_0/constraints/gau_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_hyst_1_0/constraints/hyst_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_nms_1_0/constraints/nms_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_sobel_1_0/constraints/sobel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_18/pfm_dynamic_s00_regslice_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_7/pfm_dynamic_m00_regslice_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_7/pfm_dynamic_m00_regslice_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_7/pfm_dynamic_m01_regslice_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_7/pfm_dynamic_m01_regslice_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_19/pfm_dynamic_s00_regslice_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_8/pfm_dynamic_m00_regslice_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_8/pfm_dynamic_m00_regslice_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_8/pfm_dynamic_m01_regslice_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_8/pfm_dynamic_m01_regslice_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_0/pfm_dynamic_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_0/pfm_dynamic_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_0/pfm_dynamic_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m02_regslice_0/pfm_dynamic_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m02_regslice_0/pfm_dynamic_m02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_1/pfm_dynamic_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_1/pfm_dynamic_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_1/pfm_dynamic_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m03_regslice_0/pfm_dynamic_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m03_regslice_0/pfm_dynamic_m03_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_2/pfm_dynamic_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_2/pfm_dynamic_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_2/pfm_dynamic_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m04_regslice_0/pfm_dynamic_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m04_regslice_0/pfm_dynamic_m04_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_3/pfm_dynamic_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_3/pfm_dynamic_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_auto_cc_3/pfm_dynamic_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_20/pfm_dynamic_s00_regslice_20_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_9/pfm_dynamic_m00_regslice_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_9/pfm_dynamic_m00_regslice_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_9/pfm_dynamic_m01_regslice_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_9/pfm_dynamic_m01_regslice_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_21/pfm_dynamic_s00_regslice_21_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_22/pfm_dynamic_s00_regslice_22_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_10/pfm_dynamic_m00_regslice_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m00_regslice_10/pfm_dynamic_m00_regslice_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_10/pfm_dynamic_m01_regslice_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_m01_regslice_10/pfm_dynamic_m01_regslice_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_23/pfm_dynamic_s00_regslice_23_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_24/pfm_dynamic_s00_regslice_24_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_s00_regslice_24/pfm_dynamic_s00_regslice_24_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top pfm_dynamic -part xcu250-figd2104-2L-e -mode out_of_context
OPTRACE "synth_design" END { }

rename_ref -prefix_all pfm_dynamic_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pfm_dynamic.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.runs/my_rm_synth_1/pfm_dynamic.dcp /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.ip_user_files/bd/pfm_dynamic]} {
  catch { 
    file copy -force /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_stub.v /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.ip_user_files/bd/pfm_dynamic
  }
}

if {[file isdir /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.ip_user_files/bd/pfm_dynamic]} {
  catch { 
    file copy -force /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/pfm_dynamic_stub.vhdl /home/luoyanl2/ece527_taskpar/fpga_kernels/_x.hw.xilinx_u250_xdma_201830_2/link/vivado/vpl/prj/prj.ip_user_files/bd/pfm_dynamic
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "my_rm_synth_1" END { }
