# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2.0
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/proj/xbuilds/2018.2_daily_latest/installs/lin64/Vivado/2018.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu9p-fsgd2104-2L-e ../xilinx_com_hls_copy_kernel_1_0.zip
