// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gsn_gsn,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.414000,HLS_SYN_LAT=1053288,HLS_SYN_TPT=525851,HLS_SYN_MEM=777,HLS_SYN_DSP=0,HLS_SYN_FF=5119,HLS_SYN_LUT=6648,HLS_VERSION=2020_1}" *)

module gsn (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] data;
wire   [63:0] out_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [7:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [7:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire   [7:0] gau_buf_i_q0;
wire   [7:0] gau_buf_t_q0;
wire   [7:0] sobel_buf_value_i_q0;
wire   [7:0] sobel_buf_value_t_q0;
wire   [7:0] sobel_buf_grad_i_q0;
wire   [7:0] sobel_buf_grad_t_q0;
wire    gau6_U0_ap_start;
wire    gau6_U0_ap_done;
wire    gau6_U0_ap_continue;
wire    gau6_U0_ap_idle;
wire    gau6_U0_ap_ready;
wire    gau6_U0_m_axi_gmem0_AWVALID;
wire   [63:0] gau6_U0_m_axi_gmem0_AWADDR;
wire   [0:0] gau6_U0_m_axi_gmem0_AWID;
wire   [31:0] gau6_U0_m_axi_gmem0_AWLEN;
wire   [2:0] gau6_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] gau6_U0_m_axi_gmem0_AWBURST;
wire   [1:0] gau6_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] gau6_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] gau6_U0_m_axi_gmem0_AWPROT;
wire   [3:0] gau6_U0_m_axi_gmem0_AWQOS;
wire   [3:0] gau6_U0_m_axi_gmem0_AWREGION;
wire   [0:0] gau6_U0_m_axi_gmem0_AWUSER;
wire    gau6_U0_m_axi_gmem0_WVALID;
wire   [7:0] gau6_U0_m_axi_gmem0_WDATA;
wire   [0:0] gau6_U0_m_axi_gmem0_WSTRB;
wire    gau6_U0_m_axi_gmem0_WLAST;
wire   [0:0] gau6_U0_m_axi_gmem0_WID;
wire   [0:0] gau6_U0_m_axi_gmem0_WUSER;
wire    gau6_U0_m_axi_gmem0_ARVALID;
wire   [63:0] gau6_U0_m_axi_gmem0_ARADDR;
wire   [0:0] gau6_U0_m_axi_gmem0_ARID;
wire   [31:0] gau6_U0_m_axi_gmem0_ARLEN;
wire   [2:0] gau6_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] gau6_U0_m_axi_gmem0_ARBURST;
wire   [1:0] gau6_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] gau6_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] gau6_U0_m_axi_gmem0_ARPROT;
wire   [3:0] gau6_U0_m_axi_gmem0_ARQOS;
wire   [3:0] gau6_U0_m_axi_gmem0_ARREGION;
wire   [0:0] gau6_U0_m_axi_gmem0_ARUSER;
wire    gau6_U0_m_axi_gmem0_RREADY;
wire    gau6_U0_m_axi_gmem0_BREADY;
wire   [17:0] gau6_U0_out_r_address0;
wire    gau6_U0_out_r_ce0;
wire    gau6_U0_out_r_we0;
wire   [7:0] gau6_U0_out_r_d0;
wire   [63:0] gau6_U0_out1_out_din;
wire    gau6_U0_out1_out_write;
wire    ap_channel_done_gau_buf;
wire    gau6_U0_out_r_full_n;
wire    sobel_U0_ap_start;
wire    sobel_U0_ap_done;
wire    sobel_U0_ap_continue;
wire    sobel_U0_ap_idle;
wire    sobel_U0_ap_ready;
wire   [17:0] sobel_U0_data_address0;
wire    sobel_U0_data_ce0;
wire   [17:0] sobel_U0_out_0_address0;
wire    sobel_U0_out_0_ce0;
wire    sobel_U0_out_0_we0;
wire   [7:0] sobel_U0_out_0_d0;
wire   [17:0] sobel_U0_out_1_address0;
wire    sobel_U0_out_1_ce0;
wire    sobel_U0_out_1_we0;
wire   [7:0] sobel_U0_out_1_d0;
wire    ap_channel_done_sobel_buf_grad;
wire    sobel_U0_out_1_full_n;
reg    ap_sync_reg_channel_write_sobel_buf_grad;
wire    ap_sync_channel_write_sobel_buf_grad;
wire    ap_channel_done_sobel_buf_value;
wire    sobel_U0_out_0_full_n;
reg    ap_sync_reg_channel_write_sobel_buf_value;
wire    ap_sync_channel_write_sobel_buf_value;
wire    nms_U0_ap_start;
wire    nms_U0_ap_done;
wire    nms_U0_ap_continue;
wire    nms_U0_ap_idle;
wire    nms_U0_ap_ready;
wire    nms_U0_m_axi_gmem1_AWVALID;
wire   [63:0] nms_U0_m_axi_gmem1_AWADDR;
wire   [0:0] nms_U0_m_axi_gmem1_AWID;
wire   [31:0] nms_U0_m_axi_gmem1_AWLEN;
wire   [2:0] nms_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] nms_U0_m_axi_gmem1_AWBURST;
wire   [1:0] nms_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] nms_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] nms_U0_m_axi_gmem1_AWPROT;
wire   [3:0] nms_U0_m_axi_gmem1_AWQOS;
wire   [3:0] nms_U0_m_axi_gmem1_AWREGION;
wire   [0:0] nms_U0_m_axi_gmem1_AWUSER;
wire    nms_U0_m_axi_gmem1_WVALID;
wire   [7:0] nms_U0_m_axi_gmem1_WDATA;
wire   [0:0] nms_U0_m_axi_gmem1_WSTRB;
wire    nms_U0_m_axi_gmem1_WLAST;
wire   [0:0] nms_U0_m_axi_gmem1_WID;
wire   [0:0] nms_U0_m_axi_gmem1_WUSER;
wire    nms_U0_m_axi_gmem1_ARVALID;
wire   [63:0] nms_U0_m_axi_gmem1_ARADDR;
wire   [0:0] nms_U0_m_axi_gmem1_ARID;
wire   [31:0] nms_U0_m_axi_gmem1_ARLEN;
wire   [2:0] nms_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] nms_U0_m_axi_gmem1_ARBURST;
wire   [1:0] nms_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] nms_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] nms_U0_m_axi_gmem1_ARPROT;
wire   [3:0] nms_U0_m_axi_gmem1_ARQOS;
wire   [3:0] nms_U0_m_axi_gmem1_ARREGION;
wire   [0:0] nms_U0_m_axi_gmem1_ARUSER;
wire    nms_U0_m_axi_gmem1_RREADY;
wire    nms_U0_m_axi_gmem1_BREADY;
wire   [17:0] nms_U0_data_0_address0;
wire    nms_U0_data_0_ce0;
wire   [17:0] nms_U0_data_1_address0;
wire    nms_U0_data_1_ce0;
wire    nms_U0_out_r_read;
wire    ap_sync_continue;
wire    gau_buf_i_full_n;
wire    gau_buf_t_empty_n;
wire    sobel_buf_value_i_full_n;
wire    sobel_buf_value_t_empty_n;
wire    sobel_buf_grad_i_full_n;
wire    sobel_buf_grad_t_empty_n;
wire    out_c_full_n;
wire   [63:0] out_c_dout;
wire    out_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    gau6_U0_start_full_n;
wire    gau6_U0_start_write;
wire    sobel_U0_start_full_n;
wire    sobel_U0_start_write;
wire    nms_U0_start_full_n;
wire    nms_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_sobel_buf_grad = 1'b0;
#0 ap_sync_reg_channel_write_sobel_buf_value = 1'b0;
end

gsn_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data(data),
    .out_r(out_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

gsn_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gau6_U0_m_axi_gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(gau6_U0_m_axi_gmem0_ARADDR),
    .I_ARID(gau6_U0_m_axi_gmem0_ARID),
    .I_ARLEN(gau6_U0_m_axi_gmem0_ARLEN),
    .I_ARSIZE(gau6_U0_m_axi_gmem0_ARSIZE),
    .I_ARLOCK(gau6_U0_m_axi_gmem0_ARLOCK),
    .I_ARCACHE(gau6_U0_m_axi_gmem0_ARCACHE),
    .I_ARQOS(gau6_U0_m_axi_gmem0_ARQOS),
    .I_ARPROT(gau6_U0_m_axi_gmem0_ARPROT),
    .I_ARUSER(gau6_U0_m_axi_gmem0_ARUSER),
    .I_ARBURST(gau6_U0_m_axi_gmem0_ARBURST),
    .I_ARREGION(gau6_U0_m_axi_gmem0_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gau6_U0_m_axi_gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

gsn_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(nms_U0_m_axi_gmem1_AWVALID),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(nms_U0_m_axi_gmem1_AWADDR),
    .I_AWID(nms_U0_m_axi_gmem1_AWID),
    .I_AWLEN(nms_U0_m_axi_gmem1_AWLEN),
    .I_AWSIZE(nms_U0_m_axi_gmem1_AWSIZE),
    .I_AWLOCK(nms_U0_m_axi_gmem1_AWLOCK),
    .I_AWCACHE(nms_U0_m_axi_gmem1_AWCACHE),
    .I_AWQOS(nms_U0_m_axi_gmem1_AWQOS),
    .I_AWPROT(nms_U0_m_axi_gmem1_AWPROT),
    .I_AWUSER(nms_U0_m_axi_gmem1_AWUSER),
    .I_AWBURST(nms_U0_m_axi_gmem1_AWBURST),
    .I_AWREGION(nms_U0_m_axi_gmem1_AWREGION),
    .I_WVALID(nms_U0_m_axi_gmem1_WVALID),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(nms_U0_m_axi_gmem1_WDATA),
    .I_WID(nms_U0_m_axi_gmem1_WID),
    .I_WUSER(nms_U0_m_axi_gmem1_WUSER),
    .I_WLAST(nms_U0_m_axi_gmem1_WLAST),
    .I_WSTRB(nms_U0_m_axi_gmem1_WSTRB),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(nms_U0_m_axi_gmem1_BREADY),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

gsn_gau_buf #(
    .DataWidth( 8 ),
    .AddressRange( 262144 ),
    .AddressWidth( 18 ))
gau_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(gau6_U0_out_r_address0),
    .i_ce0(gau6_U0_out_r_ce0),
    .i_we0(gau6_U0_out_r_we0),
    .i_d0(gau6_U0_out_r_d0),
    .i_q0(gau_buf_i_q0),
    .t_address0(sobel_U0_data_address0),
    .t_ce0(sobel_U0_data_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(gau_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(gau_buf_i_full_n),
    .i_write(gau6_U0_ap_done),
    .t_empty_n(gau_buf_t_empty_n),
    .t_read(sobel_U0_ap_ready)
);

gsn_gau_buf #(
    .DataWidth( 8 ),
    .AddressRange( 262144 ),
    .AddressWidth( 18 ))
sobel_buf_value_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(sobel_U0_out_0_address0),
    .i_ce0(sobel_U0_out_0_ce0),
    .i_we0(sobel_U0_out_0_we0),
    .i_d0(sobel_U0_out_0_d0),
    .i_q0(sobel_buf_value_i_q0),
    .t_address0(nms_U0_data_0_address0),
    .t_ce0(nms_U0_data_0_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(sobel_buf_value_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sobel_buf_value_i_full_n),
    .i_write(ap_channel_done_sobel_buf_value),
    .t_empty_n(sobel_buf_value_t_empty_n),
    .t_read(nms_U0_ap_ready)
);

gsn_gau_buf #(
    .DataWidth( 8 ),
    .AddressRange( 262144 ),
    .AddressWidth( 18 ))
sobel_buf_grad_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(sobel_U0_out_1_address0),
    .i_ce0(sobel_U0_out_1_ce0),
    .i_we0(sobel_U0_out_1_we0),
    .i_d0(sobel_U0_out_1_d0),
    .i_q0(sobel_buf_grad_i_q0),
    .t_address0(nms_U0_data_1_address0),
    .t_ce0(nms_U0_data_1_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(sobel_buf_grad_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sobel_buf_grad_i_full_n),
    .i_write(ap_channel_done_sobel_buf_grad),
    .t_empty_n(sobel_buf_grad_t_empty_n),
    .t_read(nms_U0_ap_ready)
);

gsn_gau6 gau6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(gau6_U0_ap_start),
    .ap_done(gau6_U0_ap_done),
    .ap_continue(gau6_U0_ap_continue),
    .ap_idle(gau6_U0_ap_idle),
    .ap_ready(gau6_U0_ap_ready),
    .m_axi_gmem0_AWVALID(gau6_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(gau6_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(gau6_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(gau6_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(gau6_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(gau6_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(gau6_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(gau6_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(gau6_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(gau6_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(gau6_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(gau6_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(gau6_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(gau6_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(gau6_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(gau6_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(gau6_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(gau6_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(gau6_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(gau6_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(gau6_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(gau6_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(gau6_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(gau6_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(gau6_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(gau6_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(gau6_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(gau6_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(gau6_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(gau6_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(gau6_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(gau6_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .data(data),
    .out_r_address0(gau6_U0_out_r_address0),
    .out_r_ce0(gau6_U0_out_r_ce0),
    .out_r_we0(gau6_U0_out_r_we0),
    .out_r_d0(gau6_U0_out_r_d0),
    .out1(out_r),
    .out1_out_din(gau6_U0_out1_out_din),
    .out1_out_full_n(out_c_full_n),
    .out1_out_write(gau6_U0_out1_out_write)
);

gsn_sobel sobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sobel_U0_ap_start),
    .ap_done(sobel_U0_ap_done),
    .ap_continue(sobel_U0_ap_continue),
    .ap_idle(sobel_U0_ap_idle),
    .ap_ready(sobel_U0_ap_ready),
    .data_address0(sobel_U0_data_address0),
    .data_ce0(sobel_U0_data_ce0),
    .data_q0(gau_buf_t_q0),
    .out_0_address0(sobel_U0_out_0_address0),
    .out_0_ce0(sobel_U0_out_0_ce0),
    .out_0_we0(sobel_U0_out_0_we0),
    .out_0_d0(sobel_U0_out_0_d0),
    .out_1_address0(sobel_U0_out_1_address0),
    .out_1_ce0(sobel_U0_out_1_ce0),
    .out_1_we0(sobel_U0_out_1_we0),
    .out_1_d0(sobel_U0_out_1_d0)
);

gsn_nms nms_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(nms_U0_ap_start),
    .ap_done(nms_U0_ap_done),
    .ap_continue(nms_U0_ap_continue),
    .ap_idle(nms_U0_ap_idle),
    .ap_ready(nms_U0_ap_ready),
    .m_axi_gmem1_AWVALID(nms_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(nms_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(nms_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(nms_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(nms_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(nms_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(nms_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(nms_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(nms_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(nms_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(nms_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(nms_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(nms_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(gmem1_WREADY),
    .m_axi_gmem1_WDATA(nms_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(nms_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(nms_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(nms_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(nms_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(nms_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(nms_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(nms_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(nms_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(nms_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(nms_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(nms_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(nms_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(nms_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(nms_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(nms_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(nms_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(nms_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(8'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(gmem1_BVALID),
    .m_axi_gmem1_BREADY(nms_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(gmem1_BRESP),
    .m_axi_gmem1_BID(gmem1_BID),
    .m_axi_gmem1_BUSER(gmem1_BUSER),
    .data_0_address0(nms_U0_data_0_address0),
    .data_0_ce0(nms_U0_data_0_ce0),
    .data_0_q0(sobel_buf_value_t_q0),
    .data_1_address0(nms_U0_data_1_address0),
    .data_1_ce0(nms_U0_data_1_ce0),
    .data_1_q0(sobel_buf_grad_t_q0),
    .out_r_dout(out_c_dout),
    .out_r_empty_n(out_c_empty_n),
    .out_r_read(nms_U0_out_r_read)
);

gsn_fifo_w64_d3_S out_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(gau6_U0_out1_out_din),
    .if_full_n(out_c_full_n),
    .if_write(gau6_U0_out1_out_write),
    .if_dout(out_c_dout),
    .if_empty_n(out_c_empty_n),
    .if_read(nms_U0_out_r_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_sobel_buf_grad <= 1'b0;
    end else begin
        if (((sobel_U0_ap_done & sobel_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sobel_buf_grad <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sobel_buf_grad <= ap_sync_channel_write_sobel_buf_grad;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_sobel_buf_value <= 1'b0;
    end else begin
        if (((sobel_U0_ap_done & sobel_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sobel_buf_value <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sobel_buf_value <= ap_sync_channel_write_sobel_buf_value;
        end
    end
end

assign ap_channel_done_gau_buf = gau6_U0_ap_done;

assign ap_channel_done_sobel_buf_grad = (sobel_U0_ap_done & (ap_sync_reg_channel_write_sobel_buf_grad ^ 1'b1));

assign ap_channel_done_sobel_buf_value = (sobel_U0_ap_done & (ap_sync_reg_channel_write_sobel_buf_value ^ 1'b1));

assign ap_done = nms_U0_ap_done;

assign ap_idle = (sobel_U0_ap_idle & nms_U0_ap_idle & gau6_U0_ap_idle & (sobel_buf_grad_t_empty_n ^ 1'b1) & (sobel_buf_value_t_empty_n ^ 1'b1) & (gau_buf_t_empty_n ^ 1'b1));

assign ap_ready = gau6_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_sobel_buf_grad = ((sobel_U0_out_1_full_n & ap_channel_done_sobel_buf_grad) | ap_sync_reg_channel_write_sobel_buf_grad);

assign ap_sync_channel_write_sobel_buf_value = ((sobel_U0_out_0_full_n & ap_channel_done_sobel_buf_value) | ap_sync_reg_channel_write_sobel_buf_value);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = nms_U0_ap_done;

assign ap_sync_ready = gau6_U0_ap_ready;

assign gau6_U0_ap_continue = gau_buf_i_full_n;

assign gau6_U0_ap_start = ap_start;

assign gau6_U0_out_r_full_n = gau_buf_i_full_n;

assign gau6_U0_start_full_n = 1'b1;

assign gau6_U0_start_write = 1'b0;

assign nms_U0_ap_continue = 1'b1;

assign nms_U0_ap_start = (sobel_buf_value_t_empty_n & sobel_buf_grad_t_empty_n);

assign nms_U0_start_full_n = 1'b1;

assign nms_U0_start_write = 1'b0;

assign sobel_U0_ap_continue = (ap_sync_channel_write_sobel_buf_value & ap_sync_channel_write_sobel_buf_grad);

assign sobel_U0_ap_start = gau_buf_t_empty_n;

assign sobel_U0_out_0_full_n = sobel_buf_value_i_full_n;

assign sobel_U0_out_1_full_n = sobel_buf_grad_i_full_n;

assign sobel_U0_start_full_n = 1'b1;

assign sobel_U0_start_write = 1'b0;

endmodule //gsn
